### ISSUE TITLE
Song playing not fully

### ISSUE THREAD

**Issue by peterGruen** [diraimondo/gmusicproxy#74] opened 2017-01-07 23:30 UTC
Hello,
I'm running gmusicproxy with the latest version on raspberry with latest jessie over LAN.

The Problem is the songs stopping before end, mostly 1minute before end.
I have streamed the songs on different Computers, like Windows VLC or Raspberry mpd.

The only error I have detected by gmusicproxy is **_connection reset_**, and from mpd: _**curl: curl failed: transfer closed with 2574314 bytes remaining to read**_.

I have reinstalled gmusicApi and gmusicproxy, same result.

**Comment by diraimondo** [comment] 2017-01-07 23:47
It could be related to the open report #56 or it could be a connection problem with the client.
- does the problem systematically happen with the same song with the same number of chopped bytes?
- if yes, can you provide the id of the song?

In report #56 there are some ids you can test: with one of them I got a very wrong reported size; could you test it. I need spare time to fix bug #56: this could fix your problem too...

**Comment by peterGruen** [comment] 2017-01-08 12:44
does the problem systematically happen with the same song with the same number of chopped bytes?
   there all different songs, actually same song by mpd: **_curl failed: transfer closed with 2052074 byte_**
   sometimes there played full, but mostly not. 
The ID :33c8e3d2-9e5c-3fe7-9e51-e7c2fb4620e8, or what ID do mean ?

**Comment by diraimondo** [comment] 2017-01-08 15:07
I mean ID like this: `Txb4xwg5m736wg6fhgpiakhrij4`

**Comment by peterGruen** [comment] 2017-01-08 16:19
Sorry, do mean the storeId ?
 u'storeId': u'Thnuo2ttavwbze7iphxynrln4iy'
What can I do with this ID ?

**Comment by diraimondo** [comment] 2017-01-08 17:05
I wanted to reproduce your problem on my system: I'm not able to do that. I can regularly get your song (Sia - Elastic Heart) with a constant size of 10336886 bytes and without any error on the client and server sides. Is there any network issues on your environment (check client-gmusicproxy connection but also gmusicproxy-Internet one)?

**Comment by abusenius** [comment] 2017-01-14 19:16
I cannot reproduce the problem with your song, but I have a similar issue with connection resets near the end of song. I have created a patch that fixed it for me - see pull request #75

**Comment by diraimondo** [comment] 2017-01-14 21:20
@peterGruen could you test the latest change in the master repository? Let us know if @abusenius fixes your problem.

**Comment by diraimondo** [comment] 2017-01-19 13:59
@peterGruen I'm going to close this report because the problem should/could be fixed by recent changes. Feel free to reopen it if you face again the same problem.

**Closed by diraimondo** 2017-01-19 13:59 UTC
